Fix travis build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -37,9 +37,11 @@ script:
  - cabal test
  - cabal check
  - cabal sdist
- - if [ -f "$SRC_TGZ" ]; then
- -    cabal install --force-reinstalls "$SRC_TGZ";
- - else
- -    echo "expected '$SRC_TGZ' not found";
- -    exit 1;
- - fi
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
